import Head from 'next/head'
import Link from 'next/link'
//image
import bannerImg from '../public/images/banners/home.png'
//components
import Banner from '@/components/Banner'
import Roi from '@/components/Roi'
import Potential from '@/components/Potential'
import Buyability from '@/components/Buyability'
import Photography from '@/components/Photography'
import Translating from '@/components/Translating'
import Platform from '@/components/Platform'
import OneStop from '@/components/OneStop'
import Partners from '@/components/Partners'
import Discover from '@/components/Discover'
import Proposal from '@/components/Proposal'

export default function Home() {

  // ====== banner title ====== //
  const newTitle = <h1 className='font-60 fw-700 font-second txt-white mb-4'>Amazon SEO Services</h1>


  // ====== banner buttons ====== //
  const cta1 = <Link className='btns homeBtn btnPrime' href="#">Get A Quote</Link>


  // ========================================== //

  const bannertext = [
    {
      title: newTitle,
      subtitle: 'The Fast Lane To Revenue Growth',
      text: 'Amazon Listing Optimization That Encourage Online Shoppers to Buy',
      subtext: 'With our performance-oriented Amazon SEO services, we help your business and your products become the number one pick of buyers worldwide.',
      discuss: cta1,
      imageban: bannerImg,
      alignclass: 'homeBanner',
      banner: 'banner'
    }
  ]

  return (
    <>
      <Head>
        <title>Amazon Square</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.png" />
      </Head>

      {/*========= Banner =========*/}

      {bannertext.map((item, i) =>
        <Banner key={i}
          title={item.title}
          subtitle={item.subtitle}
          text={item.text}
          subtext={item.subtext}
          discuss={item.discuss}
          imageban={item.imageban}
          alignclass={item.alignclass}
          banner={item.banner}
        />
      )}


      {/*========= Roi =========*/}

      <Roi />


      {/*========= Potential =========*/}

      <Potential />


      {/*========= Buyability =========*/}

      <Buyability />


      {/*========= Photography =========*/}

      <Photography />


      {/*========= Translating =========*/}

      <Translating />


      {/*========= Platform =========*/}

      <Platform />


      {/*========= OneStop =========*/}

      <OneStop />


      {/*========= Partners =========*/}

      <Partners />


      {/*========= Discover =========*/}

      <Discover />


      {/*========= Proposal =========*/}

      <Proposal />

    </>
  )
}
